"""create_document_tables

Revision ID: c09b48a8d73d
Revises: 728914296ec8
Create Date: 2026-07-31 01:07:02.684572

This migration was originally autogenerated and contained a large amount of
noise that was corrected in place:

* ~123 ``drop_index`` calls on core tables (enrollments, classes, attendance,
  device_tokens, exam_schedules, ...) whose indexes were created by
  migrations 007/024 — removed. The three intentional index changes
  (device_tokens.token, permissions.code, roles.code) are preserved.
* ``DROP TABLE audit_logs`` / ``DROP TABLE notification_preferences`` —
  removed. Those tables are created by migrations 015/019 and hardened by
  035; dropping them mid-chain broke every fresh install after this point.
* Unnamed ``drop_constraint`` + ``create_foreign_key`` churn on pre-existing
  tables (attendance_corrections, curricula, exam_schedules, grade_records,
  grading_structures, period_attendance_records, period_attendances,
  substitutions, timetable_entries) — removed. Those FKs already exist with
  the correct on-delete semantics from the tables' creating migrations.
* The remaining structural work is expressed through batch mode so the chain
  also applies cleanly on SQLite (the repo's unit-test dialect).

The real payload of this revision is unchanged: the document domain tables
(document_categories, documents, document_shares, document_versions), the
tenant ``campus_id`` foreign keys that migrations 011/016 left unconstrained
on 19 pre-existing tables, and the ``transaction_logs.idempotency_key``
unique guard.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c09b48a8d73d'
down_revision: Union[str, None] = '728914296ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tables that gained a ``campus_id`` column in migrations 011/016 without the
# corresponding tenant FK. The FK is added here under the name the naming
# convention would produce (``fk_<table>_campus_id_campuses``).
_CAMPUS_FK_TABLES = [
    "academic_years",
    "attendance_records",
    "classes",
    "device_tokens",
    "enrollments",
    "fee_dues",
    "fee_structures",
    "fee_types",
    "leave_requests",
    "notifications",
    "payments",
    "sections",
    "students",
    "subjects",
    "teacher_assignments",
    "teachers",
    "terms",
    "users",
    "workflow_instances",
]


def upgrade() -> None:
    # ── document domain tables ─────────────────────────────────────────
    op.create_table('document_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_document_categories_code'), 'document_categories',
        ['code'], unique=True,
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=20), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column(
        'uploaded_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_category_id'), 'documents', ['category_id'], unique=False)
    op.create_index(
        op.f('ix_documents_lifecycle_state'), 'documents',
        ['lifecycle_state'], unique=False,
    )
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_student_id'), 'documents', ['student_id'], unique=False)
    op.create_table('document_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_document_shares_document_id'), 'document_shares',
        ['document_id'], unique=False,
    )
    op.create_index(op.f('ix_document_shares_token'), 'document_shares', ['token'], unique=True)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True),
        server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False,
    ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_document_versions_document_id'), 'document_versions',
        ['document_id'], unique=False,
    )

    # ── tenant FKs for campus_id columns left unconstrained by 011/016 ─
    # (named so batch mode — and therefore SQLite — can express them)
    for table in _CAMPUS_FK_TABLES:
        with op.batch_alter_table(table) as batch_op:
            batch_op.create_foreign_key(
                f"fk_{table}_campus_id_campuses",
                "campuses", ["campus_id"], ["id"], ondelete="SET NULL",
            )

    # device_tokens: replace the unique constraint + plain index with a
    # single unique index (matches the ORM's unique index declaration).
    with op.batch_alter_table("device_tokens") as batch_op:
        batch_op.drop_constraint("uq_device_tokens_token", type_="unique")
        batch_op.drop_index("ix_device_tokens_token")
        batch_op.create_index("ix_device_tokens_token", ["token"], unique=True)

    # permissions/roles: promote the code index to unique.
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)

    # subjects.description: normalize TEXT → String (type change requires
    # batch mode on SQLite).
    with op.batch_alter_table("subjects") as batch_op:
        batch_op.alter_column(
            "description", existing_type=sa.TEXT(), type_=sa.String(),
            existing_nullable=True,
        )

    # transaction_logs: idempotency guard for financial replay.
    with op.batch_alter_table("transaction_logs") as batch_op:
        batch_op.create_unique_constraint(
            "uq_transaction_idempotency", ["idempotency_key"],
        )


def downgrade() -> None:
    with op.batch_alter_table("transaction_logs") as batch_op:
        batch_op.drop_constraint("uq_transaction_idempotency", type_="unique")

    with op.batch_alter_table("subjects") as batch_op:
        batch_op.alter_column(
            "description", existing_type=sa.String(), type_=sa.TEXT(),
            existing_nullable=True,
        )

    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)

    with op.batch_alter_table("device_tokens") as batch_op:
        batch_op.drop_index("ix_device_tokens_token")
        batch_op.create_index("ix_device_tokens_token", ["token"], unique=False)
        batch_op.create_unique_constraint("uq_device_tokens_token", ["token"])

    for table in reversed(_CAMPUS_FK_TABLES):
        with op.batch_alter_table(table) as batch_op:
            batch_op.drop_constraint(
                f"fk_{table}_campus_id_campuses", type_="foreignkey",
            )

    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_shares_token'), table_name='document_shares')
    op.drop_index(op.f('ix_document_shares_document_id'), table_name='document_shares')
    op.drop_table('document_shares')
    op.drop_index(op.f('ix_documents_student_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_lifecycle_state'), table_name='documents')
    op.drop_index(op.f('ix_documents_category_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_categories_code'), table_name='document_categories')
    op.drop_table('document_categories')
